# Making a Cutout of an Image at a Given Position


In astronomical image processing, we often need to crop an image into small pieces at a given location. We implement a function which crops an image into a given size.

In [50]:
import numpy as np

def crop_image(image, cr, cc, half_r = 50, half_c=50, fill_edge=True, fill_value=np.nan):
    r_left = min(half_r, cr)
    r_right = min(half_r, image.shape[0] - 1 - cr)
    c_left = min(half_c, cc)
    c_right = min(half_c, image.shape[1] - 1 - cc)


    image_slice = image[cr - r_left: cr + r_right + 1, cc - c_left: cc + c_right + 1].copy()

    if fill_edge:
        cutout = np.full( (2 * half_r + 1, 2 * half_c + 1), fill_value)
        cutout[half_r - r_left: half_r + r_right + 1, half_c - c_left: half_c + c_right + 1] = image_slice
        return cutout
    else:
        return image_slice

In [49]:
test_image = np.array([[0, 0, 0],
                       [0, 0, 0],
                       [1, 1, 1],
                       [0, 0, 0]])

# Test

In [ ]:
import matplotlib.pyplot as plt

## Crop size is larger than the image size

In [34]:
cropped_image = crop_image(test_image, cr=2, cc=1, half_r = 50, half_c=30, fill_edge=True, fill_value=np.nan)
# check cropped image shape
print(cropped_image.shape)
print('-------------------------------------------------')
# check fill value with np.nan
print(cropped_image)
print('-------------------------------------------------')
# check image center
print(cropped_image[48: 53, 28: 33])

(101, 61)
-------------------------------------------------
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
-------------------------------------------------
[[nan  0.  0.  0. nan]
 [nan  0.  0.  0. nan]
 [nan  1.  1.  1. nan]
 [nan  0.  0.  0. nan]
 [nan nan nan nan nan]]


In [35]:
# check fill value with 0
cropped_image = crop_image(test_image, cr=2, cc=1, half_r = 50, half_c=30, fill_edge=True, fill_value=0)
print(cropped_image[48: 53, 28: 33])

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [44]:
# do not fill edge
cropped_image = crop_image(test_image, cr=2, cc=1, half_r = 50, half_c=30, fill_edge=False, fill_value=0)
print(cropped_image)

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]]


## Crop size is equal to the image size

In [37]:
cropped_image = crop_image(test_image, cr=2, cc=1, half_r = 2, half_c=1, fill_edge=True, fill_value=0)
print(cropped_image)

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [0 0 0]]


In [45]:
# do not fill edge
cropped_image = crop_image(test_image, cr=2, cc=1, half_r = 2, half_c=1, fill_edge=False, fill_value=0)
print(cropped_image)

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]]


## Crop size is smaller than the image size

In [43]:
cropped_image = crop_image(test_image, cr=2, cc=1, half_r = 1, half_c=1, fill_edge=True, fill_value=np.nan)
print(cropped_image)

[[0. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]


In [42]:
cropped_image = crop_image(test_image, cr=2, cc=1, half_r = 1, half_c=0, fill_edge=True, fill_value=np.nan)
print(cropped_image)

[[0.]
 [1.]
 [0.]]


In [47]:
# do not fill edge
cropped_image = crop_image(test_image, cr=2, cc=1, half_r = 1, half_c=1, fill_edge=False, fill_value=np.nan)
print(cropped_image)

[[0 0 0]
 [1 1 1]
 [0 0 0]]
